### ISSUE TITLE
pipe support

### ISSUE THREAD

**Issue by huggla** [hadrien-psydk/pngoptimizer#1]
I would like to use pngoptimizercl on Linux but I need to be able to use pipes as input and output. Currently pngoptimizercl only seems to accept a filename, which it uses for both reading and writing. I've tried to use a fifo (named pipe) as the file given. Pngoptimizercl should have no problem reading from the fifo but that puts a lock on the fifo which prevents writing to it and pngoptimizer fails. It would be nice if pngoptimizercl could read from stdin and write to stdout but for me it would suffice to be able to give a prefix/suffix that is added to the output file name so it doesn't overwrite the input file.

**Comment by huggla** [comment]
I got following answer by e-mail:

> I could make PngOptimizer read a picture from stdin but writing to stdout would be harder as PngOptimizer needs to regularly rewind the output stream to write PNG specific information. The suffix solution should be easier to implement.

I'm not sure if it is possible to "rewind" a fifo. Wouldn't it be possible to do all writing and rewinding in memory prior to output?

**Comment by hadrien-psydk** [comment]
> Wouldn't it be possible to do all writing and rewinding in memory prior to output?
I think so. PngOptimizer stores the result file content in memory before writing it to disk, so it may be possible to write to stdout in one single write, without the need to rewind.

I will look at it. For the command line option, I propose something like: `pngoptimizercl -stdio`, mutually exclusive with `pngoptimizercl -file:""`

**Comment by huggla** [comment]
I think the standard format for command line options in Linux is like this:
--file <filename>
and/or a compact alternative like this:
-f <filename>

**Comment by hadrien-psydk** [comment]
I created a new branch to develop the feature: stdio-feature. I have something working but the code is still fresh. You may want to test that new feature but if you do not want to compile pngoptimizecl yourself, you will find a binary file here: http://psydk.org/download/pngoptimizercl-2.5-beta-linux-x64-20160905.tgz

I have yet to make this feature work on Windows.

**Comment by huggla** [comment]
It works great on Ubuntu 16.04. Thanks!

**Comment by hadrien-psydk** [comment]
Good news. Thanks for the test. I will release an official version when the Windows implementation is ready.

**Comment by hadrien-psydk** [comment]
The feature was implemented on Windows and the branch merged on master.

The feature is released on version 2.5, now officially available on http://psydk.org/pngoptimizer
