### ISSUE TITLE
[Feature request] Support for .APNG files (same format, different suffix)

### ISSUE THREAD

**Issue by vatterspun** [hadrien-psydk/pngoptimizer#10]
One developer has suggested using .APNG suffix for animated PNG files (specifically ScreenToGif).  Currently, if you add a .APNG file to PNGOptimizer, it will ignore it.  You must rename the extention

**Reasons not to do this**

In particular, Github doesn't support .APNG files and other tools may also balk at this format.  Since older browsers and Internet Explorer can still view the first frame of .PNG files, it might make sense that .PNG remains the standard.

**Reasons to do this**

If you send someone an APNG file, there's a chance they might spend a little more effort to see that it's animated.

**Comment by hadrien-psydk** [comment]
Hello vatterspun,
I'm not sure I understand your issue. PngOptimizer does support the ".apng" extension (and mixed upper case variants). May I ask you to specify your use case in a detailed fashion please? What do you mean exactly with "add a .APNG file"? Do you drag and drop an individual file? A folder? Do you pass the file as a command line argument? Are you using the GUI or the "CL" version of PngOptimizer?

**Comment by vatterspun** [comment]
As noted in my previous post, this may not be something you actually want to fix.  It might be a bad idea.

SETUP: Win7x86, PngOptimizer (GUI) v 2.0

STEPS

1. Generate a recording using ScreenToGif ( http://www.screentogif.com/ | https://github.com/NickeManarin/ScreenToGif/releases  )
2. When prompted, save to APNG (the program has an option to save to either PNG or APNG) e.g. _file.apng_
3. Launch PNGOptimizer and drag-and-drop the APNG file into the application window

DEFECT: Nothing happens.

EXPECTED BEHAVIOR: Compresses the file as it does with other animated PNG file formats

WORKAROUND: Rename the file (file.apng -> file.png)

---

For reference, here's a recent post to the ScreenToGif issue: https://github.com/NickeManarin/ScreenToGif/issues/129#issuecomment-353829082

**Comment by hadrien-psydk** [comment]
- I downloaded pngoptimizer-2.5.1-win-x86.zip
- I downloaded ScreenToGif.2.11.Portable.zip
- I did a capture with ScreenToGif
- I saved the capture as "file.apng"
- I dropped "file.apng" on PngOptimizer main window

PngOptimizer processes the file as expected:
![shot-20171226t094905](https://user-images.githubusercontent.com/7605293/34353809-b8e56bf2-ea2a-11e7-82aa-65b23ad1b4c0.png)

Are you using the latest version of PngOptimizer? (2.5.1)

**Comment by vatterspun** [comment]
No, it's actually in my previous post that I was using 2.0.  Darnit.

**Comment by hadrien-psydk** [comment]
I'm happy your use case is actually handled. Best regards and happy new year.

**Comment by vatterspun** [comment]
:) Thanks
