### ISSUE TITLE
[Feature request] TGA with 8-bit alpha-channels

### ISSUE THREAD

**Issue by Jabberwock-RU** [hadrien-psydk/pngoptimizer#12]
Hello, I am using PngOptimizer more than 10 years now, from 2007 to 2019 and I find this program really handy.
But one important feature is missing - it can't convert 32-bit TGA with alpha channels properly.

**Current behavior:**
Alpha channel of 32-bit TGA is discarded when saving to Truecolor PNG and converted to 1-bit when saving to Indexed PNG.

**Requested behavior:**
Alpha channel of 32-bit TGA should be converted to the alpha channel of Truecolor PNG.

**Background / Why this is useful:**
Some games are utilizing TGA as main image format, for textures and sprites. With this feature their resources will become easier to convert.

For example, I am maintaining the resources of the Doom 2D Forever (https://github.com/Doom2D/DF-Res), and historically we have stored files in TGA. But now PNG support was added, and it's important to convert a lot of resources from hundreds of game levels to the PNG, for the name of disk space economy.

**Sample:** [tga_alpha_sample.zip](https://github.com/hadrien-psydk/pngoptimizer/files/4002924/tga_alpha_sample.zip)

**Comment by hadrien-psydk** [comment]
I converted your sample (SHADOW_15.tga) with PngOptimizer and got a transparent PNG. To be sure I displayed the PNG on an HTML page with a red background and transparency was ok. So currently I cannot reproduce the issue :-/

What version of PngOptimizer are you using? On Windows or Linux? How do you verify that transparency is discarded or not? Maybe you have another sample that systematically leads to the problem?

**Comment by Jabberwock-RU** [comment]
Hello Hadrien,

Saturday, December 28, 2019, 6:40:41 PM, you wrote:

> I converted your sample (SHADOW_15.tga) with PngOptimizer and got a
> transparent PNG. To be sure I displayed the PNG on an HTML page with
> a red background and transparency was ok. So currently I cannot reproduce the issue
> What version of PngOptimizer are you using? On Windows or Linux?
> How do you verify that transparency is discarded or not? Maybe you
> have another sample that systematically leads to the problem?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe. 

Windows, and last version.
Right now I have made your test with html and red background, and alpha worked.
It looks like Photoshop was framed me: https://i.imgur.com/s15hT6f.png

-- 
Best regards,
 jabberwock.ru                            mailto:jabberwock.ru@gmail.com

**Comment by Jabberwock-RU** [comment]
Hello Hadrien,

So  there  IS  an  alpha channel in the converted PNGs actually,
but Photoshop did not see it and made me wrong.
Sorry for bothering.

It  would  be  great  if  you  can look at the Photoshop compatibility
instead.
I  think  there  is  some little difference in PngOptimized PNGs and standard
PNGs.  Maybe  just  one  byte, but it makes them Photoshop-incompatible.

-- 
Best regards,
 jabberwock.ru                            mailto:jabberwock.ru@gmail.com

**Comment by hadrien-psydk** [comment]
If a web browser can display the PNG correctly but not Photoshop I would say this is a bug in Photoshop. The irony is that I first created PngOptimizer in 2002 because at the time Photoshop support of PNG wasn't as good as I wanted :)

I am a bit surprised if SHADOW_15 does not work, because the converted PNG is a very standard RGBA 32-bit per pixel PNG. However I guess the other image "STBF_A" may have been converted to a palette+transparency PNG which could be a problem for Photoshop. May you send me this sample to verify please?

Unfortunately I do not use Photoshop anymore. Last time I tried it was the demo version, several years ago. I did not like that they switched to a subscription model, the performance was horrible (mouse cursor slowing down when hovering a picture) and in 2014 I switched to Linux. If I am brave enough I could subscribe and cancel after a few days (the first seven days are free).

Maybe there are other software that would be suitable for your needs regarding these textures? Krita for example, or Gimp, though Gimp UI is still a problem. Another solution would be to keep textures as editable files in the native format of your graphics editor, and convert to PNG only when exporting for testing and packaging the game.

**Comment by Jabberwock-RU** [comment]
I guess it was a Photoshop problem all the way and it made me wrong.
SHADOW_15 was a wrong sample too, let's forget about it, problem was on my side.

But STBF* are more interesting.
PngOptimizer-converted STBFs shows a black background with no visible alpha-channel in the Photoshop and in the browser without HTML-wrapping, but they are passing browser "background:red" test.
STBF_A_PS_converted is working good in the Photoshop.

If you can fix their behavior in PS, it would be great, but now, when I know there was just a PS problem, I can build a workaround, so don't worry much.

[STBF.zip](https://github.com/hadrien-psydk/pngoptimizer/files/4009919/STBF.zip)
![STBF_A_PS_converted](https://user-images.githubusercontent.com/2558067/71589204-18f21200-2b35-11ea-92b4-6ea7ab9a219b.png)
P.S. I have sent you STBF* yesterday through the mail, but it looks like github did not attached them.
P.P.S. Happy New Year!

**Comment by hadrien-psydk** [comment]
Thank you for the explanation about SHADOW_15, it makes sense now.

I've been looking at STBF_A. When I convert the TGA, PngOptimizer outputs a 24-bit RGB PNG with a special information, a "tRNS" chunk, that tells black is transparent. STBF_A_PS_converted, on the other hand, is a paletted image, where the tRNS chunk tells which color indices are transparent.

I guess Photoshop does not like 24-bit RGB + transparent color PNGs. I tested with Krita and Gimp and they both handle well this kind of transparent PNG.

Adobe has a [bug report form](https://www.adobe.com/products/wishform.html), maybe you could submit them this issue.

On my side, maybe I could think of an option in the future in the same way there is a "avoid grey+simple transparency (IE6 bug)" option (the Internet Explorer 6 reference is probably deprecated now :))

Anyway, I will close the ticket. Good luck with your project, Jabberwock-RU. С новым годом :)
