### ISSUE TITLE
Image that currently fails to be optimized

### ISSUE THREAD

**Issue by devedse** [hadrien-psydk/pngoptimizer#17]
Hello,

I was trying to optimize an image using pngoptimizer and it results in an image which isn't equal to the source. It did work with a bunch of other tools but for some reason pngoptimizer fails.

I've attached the image here:
![TimelineSelector](https://user-images.githubusercontent.com/2350015/123245377-0ddb3080-d4e5-11eb-9530-31bed8b4dae9.png)
[TimelineSelector.zip](https://github.com/hadrien-psydk/pngoptimizer/files/6708307/TimelineSelector.zip)

I use the following command to optimize the image:
`-KeepPhysicalPixelDimensions -file:input.png`

**Comment by devedse** [comment]
Here's the output image:
![PngOptimizer_4jbrzp0w](https://user-images.githubusercontent.com/2350015/123245658-5397f900-d4e5-11eb-87cc-fdd6478e35bb.png)

**Comment by hadrien-psydk** [comment]
Hello @devedse, thank you for informing me about this issue.

I tested your image and it triggers a very specific bug that went unnoticed for years. Congratulations :)

I will work on a solution.

**Comment by hadrien-psydk** [comment]
It should be fixed by commit 1df67311e6a0013f9d632001e1415ccff1e91107
I will close the ticket when I release an official version.

**Comment by hadrien-psydk** [comment]
v2.7 is out, I am closing the ticket.
