### ISSUE TITLE
[Regression] PngOptimizer v2.5 doesn't save start position

### ISSUE THREAD

**Issue by TJL73** [hadrien-psydk/pngoptimizer#4]
PngOptimizer v2.5 doesn't save the start position of the window and opens always at the center of the screen.

Previous versions have always worked properly, reopening everytime in last place.

**Comment by hadrien-psydk** [comment]
TJL73, could you please test that new version and confirm that the bug is fixed, please?
http://psydk.org/download/pngoptimizer-2.5.1-win-x64.zip

**Comment by TJL73** [comment]
Hi Hadrien,

now it seems to work fine!

Thank you.

Best regards,
TJL73


2017-02-13 19:47 GMT+01:00 Hadrien <notifications@github.com>:

**Comment by hadrien-psydk** [comment]
Thanks for your feedback TJL73. I will update the download page.
