### ISSUE TITLE
Replace deprecated GTK3 functions with modern counterparts

### ISSUE THREAD

**Issue by kargaroc** [hadrien-psydk/pngoptimizer#5]
gtk_menu_popup() is deprecated since GTK 3.22, and causes this to fail to build on Arch.  If you remove -Werror it builds and runs just fine, but soon this will be removed and will have to be replaced.

**Comment by hadrien-psydk** [comment]
Thank you for reporting the problem.
It's not easy to work with GTK+ and its breakable API. It seems that `gtk_menu_popup()` should be replaced with `gtk_menu_popup_at_pointer()`, but that new function is only present in GTK 3.22 and is marked as "Unstable" in the documentation. I cannot test it yet as my system is still on 3.20 but hopefully I will be able to upgrade the code when Ubuntu 17.04 is released.
