### ISSUE TITLE
[Feature request] Overwrite files only on change

### ISSUE THREAD

**Issue by Milania1** [hadrien-psydk/pngoptimizer#7]
**Current behaviour**
When using PngOptimizer[CL] to compress all files in a folder, every `*.png` file changes even though the size did not change.

**Requested functionality**
It would be cool if only files which were actually compressed would be changed, i.e. files with a compression rate of 1 are left untouched. This might be realized as an option or is applied automatically. Since no harm is done when a file stays unmodified, I would, personally, vote for the later.

**Use case**
Currently, I use the optimizer in a deployment script to compress all files in a folder via `PngOptimizerCL -file:"folder"`. Later, all changed files in the folder are uploaded to a webserver. Due to the fact that the optimizer changes every file on each run, even though no additional compression was achieved, every file gets uploaded each time again.

This is not a too urgent issue fore me. My approach is currently working, it just introduces a bit too much traffic. But it would be cool to have the feature and might be helpful to others as well.

**Comment by kreuvf** [comment]
You could work around the issue without causing traffic by saving the output to a temporary directory. Then, you can compare (size? hash?) the files, move only differing files and destroy the temporary folder and its content.

**Comment by hadrien-psydk** [comment]
Hi kreuvf. Your feature request is interesting. I'll take a look.

**Comment by hadrien-psydk** [comment]
Milania1, I committed an implementation of the feature your are requesting. If you are on Linux, are you able to build PngOptimizer from git in order to test the feature?

**Comment by Milania1** [comment]
Wow, very cool that you implemented this feature. I just build the pngoptimizer and the pngoptimizercl on Ubuntu 16.04 and they both work as intended. For already optimized files the log shows now `(unmodified)` at the end, e.g.

```
Optimizing content-blog/Mathematics/FEDIntroduction_FilterSignal.png  (OK) 1779 bytes -> 1779 bytes (unmodified)
Optimizing content-blog/Mathematics/FEDIntroduction_FilterTaus.png  (OK) 10831 bytes -> 10831 bytes (unmodified)
```
and the modification date of the file remains the same. This is exactly what I had in mind.

Thank you very much!

**Comment by hadrien-psydk** [comment]
Thank you for testing :) I will update the changelog.
