### ISSUE TITLE
Request: include both GUI and CL versions in the installers

### ISSUE THREAD

**Issue by JobLeonard** [hadrien-psydk/pngoptimizer#8]
I just installed the PngOptimizer from a `.deb` file. Works great as a GUI, but then I wanted to try it from the command line (you know, in case I need it in a script), but then I noticed `pngoptimizer` just opens the GUI again and that the command line version was not installed.

Of course, it was trivial to download the zip and add it myself, so everything is working. And it makes perfect sense to have a separate zip file for the people who want the CL but don't need the GUI (like on a server-side script).

However, on the other side of the coin, when using the GUI version, I don't see a reason to _not_ include the CL version too. I'm sure the added size for the CL is at most a few hundred KiB, which is unlikely to an issue for anyone working with dozens of huge PNGs, and at the same time it _would_ make things a little bit more convenient.

**Comment by hadrien-psydk** [comment]
Hi Job,
For the Windows version, as it is aimed to be a standalone version, it makes sense to just embed a single .exe file in the archive. For the Linux deb version, as it is aimed to be installed, I agree it could embed both PngOptimizer executables. Thank you for your suggestion.

**Comment by hadrien-psydk** [comment]
A new version was released with that change : https://psydk.org/pngoptimizer
